-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accounts
(
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    first_name character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    last_login timestamp(6) without time zone,
    last_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_num character varying(15) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default",
    seller_account boolean,
    updated_at timestamp(6) without time zone,
    CONSTRAINT accounts_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.admin_activities
(
    activity_id bigserial NOT NULL,
    action_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    admin_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    description text COLLATE pg_catalog."default",
    entity_id bigint,
    entity_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT admin_activities_pkey PRIMARY KEY (activity_id)
);

CREATE TABLE IF NOT EXISTS public.cart
(
    cart_id bigserial NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    total_price numeric(10, 2),
    updated_at timestamp(6) without time zone,
    CONSTRAINT cart_pkey PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS public.cart_products
(
    id bigserial NOT NULL,
    cart_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    order_id bigint,
    price_at_time numeric(10, 2) NOT NULL,
    quantity integer NOT NULL,
    variant_id bigint NOT NULL,
    CONSTRAINT cart_products_pkey PRIMARY KEY (id),
    CONSTRAINT uk_cart_variant UNIQUE (cart_id, variant_id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    category_id bigserial NOT NULL,
    category_image character varying(255) COLLATE pg_catalog."default",
    category_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    parent_category_id bigint,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT uk_41g4n0emuvcm3qyf1f6cn43c0 UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    region_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    is_other boolean DEFAULT false,
    CONSTRAINT cities_pkey PRIMARY KEY (id),
    CONSTRAINT unique_city UNIQUE (name, region_code),
    CONSTRAINT unique_city_region UNIQUE (name, region_code)
);

COMMENT ON TABLE public.cities
    IS 'Egyptian cities linked to regions';

COMMENT ON COLUMN public.cities.region_code
    IS 'Foreign key reference to regions.region_code';

CREATE TABLE IF NOT EXISTS public.coupons
(
    coupon_id bigserial NOT NULL,
    coupon_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255) COLLATE pg_catalog."default",
    discount_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    discount_value numeric(10, 2) NOT NULL,
    is_active boolean,
    max_discount_amount numeric(10, 2),
    min_purchase_amount numeric(10, 2),
    updated_at timestamp(6) without time zone,
    usage_limit integer,
    used_count integer,
    valid_from timestamp(6) without time zone NOT NULL,
    valid_until timestamp(6) without time zone NOT NULL,
    CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id),
    CONSTRAINT uk_f1u99ssbdsqass9ntq968codg UNIQUE (coupon_code)
);

CREATE TABLE IF NOT EXISTS public.idempotency_keys
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    endpoint character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    request_hash character varying(64) COLLATE pg_catalog."default",
    response_body text COLLATE pg_catalog."default",
    user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id),
    CONSTRAINT uk_idempotency_key_user_endpoint UNIQUE (key, user_email, endpoint)
);

CREATE TABLE IF NOT EXISTS public.images
(
    image_id bigserial NOT NULL,
    created_at timestamp(6) without time zone,
    image_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_primary boolean,
    product_id bigint NOT NULL,
    variant_id bigint,
    CONSTRAINT images_pkey PRIMARY KEY (image_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id bigserial NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    order_date timestamp(6) without time zone,
    order_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default",
    payment_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    phone_num character varying(15) COLLATE pg_catalog."default" NOT NULL,
    total_price numeric(10, 2) NOT NULL,
    updated_at timestamp(6) without time zone,
    city character varying(100) COLLATE pg_catalog."default",
    region character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

COMMENT ON COLUMN public.orders.city
    IS 'City/locality within the region (e.g., New Cairo, Helwan)';

COMMENT ON COLUMN public.orders.region
    IS 'Egypt governorate/region (e.g., Cairo, Giza, Alexandria)';

CREATE TABLE IF NOT EXISTS public.product_variants
(
    variant_id bigserial NOT NULL,
    color character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    price numeric(10, 2) NOT NULL,
    product_id bigint NOT NULL,
    size character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sku character varying(50) COLLATE pg_catalog."default",
    stock_quantity integer NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT product_variants_pkey PRIMARY KEY (variant_id),
    CONSTRAINT uk_q935p2d1pbjm39n0063ghnfgn UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id bigserial NOT NULL,
    base_price numeric(10, 2) NOT NULL,
    category_id bigint,
    created_at timestamp(6) without time zone,
    description text COLLATE pg_catalog."default",
    is_active boolean,
    product_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_rating numeric(2, 1),
    seller_id bigint,
    updated_at timestamp(6) without time zone,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    replaced_by_token character varying(500) COLLATE pg_catalog."default",
    revoked boolean NOT NULL,
    token character varying(500) COLLATE pg_catalog."default" NOT NULL,
    user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT idx_refresh_token_token UNIQUE (token),
    CONSTRAINT uk_ghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.regions
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    region_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT regions_pkey PRIMARY KEY (id),
    CONSTRAINT regions_region_code_key UNIQUE (region_code)
);

COMMENT ON TABLE public.regions
    IS 'Egyptian governorates/regions';

COMMENT ON COLUMN public.regions.region_code
    IS 'ISO code for the region (unique)';

CREATE TABLE IF NOT EXISTS public.reviews
(
    review_id bigserial NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_id bigint NOT NULL,
    rating integer NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id)
);

CREATE TABLE IF NOT EXISTS public.sellers
(
    seller_id bigserial NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    rating numeric(3, 2),
    seller_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sellers_pkey PRIMARY KEY (seller_id)
);

CREATE TABLE IF NOT EXISTS public.store_settings
(
    id bigserial NOT NULL,
    store_address character varying(255) COLLATE pg_catalog."default",
    store_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    store_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    store_phone character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT store_settings_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cart
    ADD CONSTRAINT fkpxh1c2476to2ygwqhsaphl1fj FOREIGN KEY (email)
    REFERENCES public.accounts (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart_products
    ADD CONSTRAINT fk934i1g0jw521gfcdpukayxk12 FOREIGN KEY (variant_id)
    REFERENCES public.product_variants (variant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart_products
    ADD CONSTRAINT fkk6r8oo5dimw364x57t8rvafap FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart_products
    ADD CONSTRAINT fknlhjc091rdu9k5c8u9xwp280w FOREIGN KEY (cart_id)
    REFERENCES public.cart (cart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cities
    ADD CONSTRAINT fk_cities_region FOREIGN KEY (region_code)
    REFERENCES public.regions (region_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_region_code
    ON public.cities(region_code);


ALTER TABLE IF EXISTS public.images
    ADD CONSTRAINT fk4yevkhjwvv9opb40rancxeq9l FOREIGN KEY (variant_id)
    REFERENCES public.product_variants (variant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.images
    ADD CONSTRAINT fkghwsjbjo7mg3iufxruvq6iu3q FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk7bkchuyfb1m6sv3529k8hl33r FOREIGN KEY (email)
    REFERENCES public.accounts (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT fkosqitn4s405cynmhb87lkvuau FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fkepbha8uixgrmnejm27n6e1kkd FOREIGN KEY (seller_id)
    REFERENCES public.sellers (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id)
    REFERENCES public.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fkfj5s1l2ggp03yunsxuheq4upv FOREIGN KEY (email)
    REFERENCES public.accounts (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fkpl51cejpw4gy5swfar8br9ngi FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sellers
    ADD CONSTRAINT fkl1wuow2v0lqlhe0xgpimtkhfn FOREIGN KEY (email)
    REFERENCES public.accounts (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;